quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/bakerychantillydb
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.max-size=16

# Configuración de Hibernate ORM
#drop-and-create : Para el inicio de todo el proyecto; para la sincronización
#luego lo puedes cambiar a update
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Configuración del servidor
quarkus.http.port=8080
quarkus.jvm.args=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED

# Configuración de JWT para GENERACIÓN (Uso Simétrico HMAC)
mallrye.jwt.new-token.key.location=secret.key
smallrye.jwt.new-token.signature-algorithm=HS256
smallrye.jwt.new-token.issuer=https://pasteleria.com

#-----------------------PERMISOS PARA PETICIONES---------------------------------
# Habilita el soporte CORS
quarkus.http.cors=true
# Especifica los orígenes permitidos (URL de React/Vite)
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# ==============================
# 📧 CONFIGURACIÓN DEL MAILER
# ==============================
quarkus.mailer.from=${QUARKUS_MAILER_FROM}
quarkus.mailer.username=${QUARKUS_MAILER_USERNAME}
quarkus.mailer.password=${QUARKUS_MAILER_PASSWORD}
quarkus.mailer.host=${QUARKUS_MAILER_HOST:smtp.gmail.com}
quarkus.mailer.port=${QUARKUS_MAILER_PORT:465}
quarkus.mailer.ssl=${QUARKUS_MAILER_SSL:true}
quarkus.mailer.auth-methods=LOGIN
quarkus.mailer.mock=false

# Debug
quarkus.log.category."io.quarkus.mailer".level=DEBUG
quarkus.log.category."io.vertx.mailclient".level=DEBUG
quarkus.log.category."io.vertx".level=DEBUG

