services:
  bakery-db:
    image: mysql:8.0
    container_name: bakery-db
    restart: always
    environment:
      MYSQL_DATABASE: bakerychantillydb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"